apiVersion: batch/v1
kind: CronJob
metadata:
  name: seed-cronjob
spec:
  schedule: "*/3 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: seed-creator
            image: ttl.sh/test-docker-helmv4:24h
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "/scripts/seed-script.sh"]
            env:
            - name: HOLLOW_KUBECONFIG
              value: /etc/kube/hollow/hollow-config
            - name: GARDEN_KUBECONFIG
              value: /etc/kube/garden/garden-config
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: example-volume
              mountPath: /example/gardener-local
            - name: dev-setup-volume
              mountPath: /dev-setup/gardenconfig/components/credentials/secret-project-garden
            - name: charts-volume
              mountPath: /charts/gardener/gardenlet
            - name: templates-volume
              mountPath: /charts/gardener/gardenlet/templates
            - name: hollow-volume
              mountPath: /etc/kube/hollow
            - name: garden-volume
              mountPath: /etc/kube/garden
          restartPolicy: Never
          volumes:
          - name: script-volume
            configMap:
              name: seed-script
              defaultMode: 0755
          - name: example-volume
            configMap:
              name: example-config
              defaultMode: 0755
          - name: dev-setup-volume
            configMap:
              name: dev-setup-config
              defaultMode: 0755
          - name: charts-volume
            configMap:
              name: charts-config
              defaultMode: 0755
          - name: templates-volume
            configMap:
              name: templates-config
              defaultMode: 0755
          - name: hollow-volume
            secret:
              secretName: hollow-kubeconfig
              items:
              - key: kubeconfig
                path: hollow-config
          - name: garden-volume
            secret:
              secretName: garden-kubeconfig
              items:
              - key: kubeconfig
                path: garden-config